apiVersion: apps/v1
kind: Deployment
metadata:
  name: dipticapstone
  labels:
    app: dipticapstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dipticapstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dipticapstone
    spec:
      containers:
        - image: diptinwm/dipticapstone
          imagePullPolicy: Always
          name: dipticapstone
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dipticapstone
  labels:
    app: dipticapstone
spec:
  type: LoadBalancer
  selector:
    app: dipticapstone
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
