apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharadcapstone
  labels:
    app: sharadcapstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sharadcapstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sharadcapstone
    spec:
      containers:
        - image: sharadyadav28/sharadcapstone
          imagePullPolicy: Always
          name: sharadcapstone
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: sharadcapstone
  labels:
    app: sharadcapstone
spec:
  type: LoadBalancer
  selector:
    app: sharadcapstone
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
