apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharadcapstone1
  labels:
    app: sharadcapstone1
  namespace: default
spec:
  replicas: 2
  progressDeadlineSeconds: 1200
  selector:
    matchLabels:
      app: sharadcapstone1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sharadcapstone1
    spec:
      containers:
        - image: sharadyadav28/sharadcapstone1
          imagePullPolicy: Always
          name: sharadcapstone1
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: sharadcapstone1
  labels:
    app: sharadcapstone1
spec:
  type: LoadBalancer
  selector:
    app: sharadcapstone1
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
